services:
  - type: worker
    name: telegram_fitness_bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: FIREBASE_KEY_PATH
        sync: false
